blueprint_chat.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request
import requests
import json
import database as db
from datetime import datetime

bp_chat = Blueprint("bp_chat",__name__)

@bp_chat.route('/private',methods=["POST","GET"])
def content_private_chat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    if session['role'] == 'user':
        query = """
            select *
            from pesan
            where pengirimId like '%s' or penerimaId like '%s'
        """%(session['userId'],session['userId'])
    else:
        user = request.args.get("userId")
        query = """
            select *
            from pesan
            where pengirimId like '%s' or penerimaId like '%s'
        """%(user,user)
    df = db.df_query(query)

    if len(df) == 0:
        query = """
        SELECT userId FROM users
        where role like 'dokter'
        ORDER BY RANDOM() LIMIT 1
        """
        dokter = db.execute_query_one(query)
        query ="""
        insert into hub values('%s','%s')
        """%(dokter,session['userId'])
        db.execute_query(query)
        if session['role'] == 'user':
            return render_template('content_private_chat.html')
        else:
            return render_template('content_private_chat.html',user=user)
    else :
        array_chat = df.values.tolist()
        if session['role'] == 'user':
            return render_template('content_private_chat.html',array_chat=array_chat)
        else:
            return render_template('content_private_chat.html',array_chat=array_chat,user=user)


@bp_chat.route('/send',methods=["POST","GET"])
def content_send_chat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    if session['role'] == 'user':
        query ="""
        select count(*)
        from pesan
        """
        jml = db.execute_query_one(query)
        jml = jml+1
        query = """
        select dokId
        from hub
        where pasId like '%s'
        """%(session['userId'])
        dokter = db.execute_query_one(query)
        isi = request.form.get("chat")
        tl = datetime.today().strftime('%Y-%m-%d')
        hl = datetime.today().strftime('%H:%M')
        query = """
        insert into pesan values('%s','%s','%s','%s','%s','%s','')
        """%(jml,session['userId'],dokter,isi,tl,hl)
        db.execute_query(query)

        return redirect('/private')

    else:
        query ="""
        select count(*)
        from pesan
        """
        jml = db.execute_query_one(query)
        jml = jml+1
        user = request.args.get('user')
        isi = request.form.get("chat")
        tl = datetime.today().strftime('%Y-%m-%d')
        hl = datetime.today().strftime('%H:%M')
        query = """
        insert into pesan values('%s','%s','%s','%s','%s','%s','')        
        """%(jml,session['userId'],user,isi,tl,hl)
        db.execute_query(query)

        return redirect('/private?userId='+user)

@bp_chat.route('/list_chat',methods=["POST","GET"])
def content_list_chat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query = """
    select pasId
    from hub
    where dokId like '%s'
    """%(session['userId'])
    df = db.df_query(query)
    if len(df) == 0:
        return render_template('content_dokter_user_chat.html')
    else:
        users=''
        list_user = df.values.tolist()
        a = 0
        for i in list_user:
            query="""
            select *
            from users
            where userId like '%s'
            """%(i[0])
            df = db.df_query(query)
            df = df.values.tolist()
            if a == 0:
                users = df
            else:
                users.append(df)
            a=a+1
        return render_template('content_dokter_user_chat.html',pasien=users)

blueprint_login.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request
import requests
import json
import database as db


bp_login = Blueprint("bp_login",__name__)

@bp_login.route("/login",methods=["POST","GET"])
def login():

    email = request.form.get("email")
    password = request.form.get("password")
    query = '''
    select *
    from users
    where email like '%s' and pass like '%s'
    '''%(str(email),str(password))
    user = db.df_query(query)

    if not user.empty:
        parsed = user.to_json(orient="records")
        hasil = json.loads(parsed)
        session["google_login"] = email
        for i in hasil[0].items():
            if str(i[0]) != 'pass':
                session[i[0]] = i[1]
    else :
        print('user not found')

    return redirect("/")  

@bp_login.route("/logout")
def logout():
    session.clear()
    return redirect("/")

blueprint_profile.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request
import requests
import json
import database as db
import pandas as pd
from flask_paginate import Pagination, get_page_parameter

PER_PAGES = 5
bp_profile = Blueprint("bp_profile",__name__)

@bp_profile.route("/user-profile",methods=["POST","GET"])
def user_profile():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    userId = session['userId']
    query = '''
    
    select *
    from users
    where userId like '%s'
    
    '''%(str(userId))
    user = db.df_query(query)
    parsed = user.to_json(orient="records")
    user_json = json.loads(parsed)
    
    return render_template('content_user_profile.html',user = user_json[0])

@bp_profile.route('/update-users', methods=['POST',"GET"])
def update_users():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    hasil = request.form.to_dict(flat=False)
    
    string = ""
    for i in hasil.items():
        if len(i[1][0]) > 0 :
            qry = str(i[0])+" = '%s',"%(i[1][0])
            string = string+qry

    userId = session['userId']
    query = """
    UPDATE users
    SET %s
    WHERE userId = '%s'
    """%(string[:-1],userId)
    db.execute_query(query)
    return redirect("/user-profile")


@bp_profile.route('/list_user', methods=['POST',"GET"])
def list_users():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query = '''
    select *
    from users
    where role like 'user'
    '''
    all_user = db.df_query(query)
    list_user = all_user.values.tolist()
    return render_template('content_admin_list_user.html',list_user=list_user)


@bp_profile.route('/delete_list_user', methods=['POST',"GET"])
def delete_list_users():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    userId = request.args.get("userId")
    query = """
    delete from users
    where userId like '%s'
    """%(userId)
    db.execute_query(query)

    return redirect("/list_user")

#################################################################################penyakit

@bp_profile.route('/list_penyakit', methods=['POST',"GET"])
def list_penyakit():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    search = False
    q = request.args.get('q')
    if q:
        search = True

    page = request.args.get(get_page_parameter(), type=int, default=1)

    query = '''
    select *
    from penyakit
    '''
    all_penyakit = db.df_query(query)
    list_penyakit = all_penyakit.values.tolist()

    i=(page-1)*PER_PAGES
    penyakit_page = list_penyakit[i:i+5]
    pagination = Pagination(page=page,per_page=PER_PAGES, total=len(list_penyakit), search=search, record_name='List')

    return render_template('content_admin_list_penyakit.html',penyakit = penyakit_page, pagination=pagination,css_framework='bootstrap4')

@bp_profile.route('/delete_penyakit', methods=['POST',"GET"])
def delete_penyakit():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    penyakitId = request.args.get("penyakitId")
    query = """
    delete from penyakit
    where penyakitId like '%s'
    """%(penyakitId)
    db.execute_query(query)
    query = """
    delete from relasi 
    where penyakitId like '%s'
    """%(penyakitId)
    db.execute_query(query)

    return redirect("/list_penyakit")

@bp_profile.route('/page_add_penyakit', methods=['POST',"GET"])
def page_add_penyakit():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query = '''
    select *
    from gejala
    '''
    all_gejala = db.df_query(query)
    list_gejala = all_gejala.values.tolist()

    return render_template('content_admin_add_penyakit.html',gejala=list_gejala)

@bp_profile.route('/add_penyakit', methods=['POST',"GET"])
def add_penyakit():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    data = request.form.getlist('gejalabox')
    name = request.form.get("name")
    keterangan = request.form.get("keterangan")
    level = request.form.get("level")
    query="""
    select count(*)
    from penyakit
    """
    id = db.execute_query_one(query)
    id = id+1
    id = 'R'+str(id)
    query="""
    insert into penyakit values('%s','%s','%s','%s','')
    """%(id,name,keterangan,level)
    db.execute_query(query)
    for i in data:
        query = """
        insert into relasi values ('%s','%s')
        """%(id,i)
        db.execute_query(query)

    return redirect('/list_penyakit')


#################################################################################gejala

@bp_profile.route('/list_gejala', methods=['POST',"GET"])
def list_gejala():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    page = request.args.get(get_page_parameter(), type=int, default=1)
    query = '''
    select *
    from gejala
    '''
    all_gejala = db.df_query(query)
    list_gejala = all_gejala.values.tolist()
    i=(page-1)*PER_PAGES
    gejala_page = list_gejala[i:i+5]
    pagination = Pagination(page=page,per_page=PER_PAGES, total=len(list_gejala), record_name='List')

    return render_template('content_admin_list_gejala.html',gejala = gejala_page,pagination = pagination)

@bp_profile.route('/delete_gejala', methods=['POST',"GET"])
def delete_gejala():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    gejalaId = request.args.get("gejalaId")
    query = """
    delete from gejala
    where gejalaId like '%s'
    """%(gejalaId)
    db.execute_query(query)
    query = """
    delete from relasi
    where gejalaId like '%s'
    """%(gejalaId)
    db.execute_query(query)
    return redirect("/list_gejala")

@bp_profile.route('/page_add_gejala', methods=['POST',"GET"])
def page_add_gejala():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    return render_template('content_admin_add_gejala.html')


@bp_profile.route('/add_gejala', methods=['POST',"GET"])
def add_gejala():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')
    name = request.form.get("name")
    pertanyaan = request.form.get("pertanyaan")
    query="""
    select count(*)
    from gejala
    """
    id = db.execute_query_one(query)
    id = id+1
    id = 'G'+str(id)
    query="""
    insert into gejala values ('%s','%s','%s')
    """%(str(id),str(name),str(pertanyaan))
    db.execute_query(query)

    return redirect('/list_gejala')

#######################################################drug

@bp_profile.route('/list_drug', methods=['POST',"GET"])
def list_drug():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    page = request.args.get(get_page_parameter(), type=int, default=1)
    query = '''
    select *
    from obat
    '''
    all_obat = db.df_query(query)
    list_obat = all_obat.values.tolist()
    i=(page-1)*PER_PAGES
    obat_page = list_obat[i:i+5]
    pagination = Pagination(page=page,per_page=PER_PAGES, total=len(list_obat), record_name='List')

    return render_template('content_admin_list_drug.html',obat = obat_page,pagination = pagination)
 
@bp_profile.route('/delete_obat', methods=['POST',"GET"])
def delete_obat():

    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    obatId = request.args.get("obatId")
    query = """
    delete from obat
    where obatId like '%s'
    """%(obatId)
    db.execute_query(query)

    return redirect('/list_drug')

@bp_profile.route('/page_add_obat', methods=['POST',"GET"])
def page_add_obat():
    if "google_login" not in session:
        restricted_message = ""
        return render_template('login.html')

    query="""
    
    select penyakitId,name
    from penyakit
    
    
    """
    df = db.df_query(query)
    df = df.values.tolist()

    return render_template('content_admin_add_obat.html',penyakit=df)

@bp_profile.route('/add_obat', methods=['POST',"GET"])
def add_obat():

    name = request.form.get("name")
    pertanyaan = request.form.get("pertanyaan")
    penyakit = request.form.get("penyakit")

    query="""
    select count(*)
    from obat
    """
    id = db.execute_query_one(query)
    id = id+1
    id = 'B'+str(id)
    
    
    query ="""
    
    insert into obat values ("%s","%s","%s","%s")
    
    """%(id,penyakit,name,pertanyaan)

    db.execute_query(query)

    

    return redirect('/list_drug')

# for i in hasil.items():
#     if len(i[1][0]) > 0 :
#         if i[1][0].isnumeric():
#             qry = str(i[0])+" = %s,"%(i[1][0])
#         else:
#             qry = str(i[0])+" = '%s',"%(i[1][0])
#         print(qry)
#         string = string+qry

blueprint_register.py
from flask import Blueprint, render_template, redirect, url_for, send_file,session, abort, redirect, request
import requests
import json
import database as db
from datetime import datetime
from uuid import uuid4

bp_register = Blueprint('bp_register', __name__)

@bp_register.route('/register')
def register():

    return render_template('register.html')


@bp_register.route('/register-users', methods=['POST'])
def register_user():

    email = request.form.get("email")
    name = request.form.get("name")
    psw = request.form.get("psw")
    psw2 = request.form.get("psw-repeat")

    if '@' not in email and len(email) <5:
        return redirect("/register")
    if len(psw) < 8 :
        return redirect("/register")
    if psw != psw2:
        return redirect("/register")

    query = '''
    
    select count(*)
    from users
    
    '''
    
    #createuserID
    tl = datetime.today().strftime('%Y%m%d')
    hasil = db.execute_query_one(query)
    hasil = hasil+1
    userid = 'usr'+str(tl)+str(hasil)
    role = 'user'
    socket = uuid4().hex

    insert = """
    
    insert into users values('%s','%s','%s','%s','%s','','','','','','%s')

    """%(str(userid),str(name),str(psw),str(role),str(email),str(socket))

    print(insert)

    db.execute_query(insert)

    

    return redirect("/")

templates/content_admin_homepage.html
{% extends 'template_base.html' %}
{% block title %}Admin - Pardoc{% endblock %} 
{% block content %} 


{% with messages = get_flashed_messages() %}
{% if messages %}
<section class="testimonials">
<div class="row">
	<div class="large-12 large-centered column">
	<h3>ERROR</h3>
	<span>
	{% for message in messages %}
	{{ message }}
	{% endfor %}
	</span><p></p>
</div>
</div>
</section>
{% endif %}
{% endwith %}

<div class="container">
	<div class="btnListUser col-12">
		<a href="{{ url_for('bp_profile.list_users')}}">List User</a>
	</div>
	
	<div class="row justify-content-center">
		<div class="col-4">
			<div class="btnListDisease w-100">
				<a href="{{ url_for('bp_profile.list_penyakit')}}">List Disease</a>
			</div>
		</div>
		<div class="col-4">
			<div class="btnListSymtoms w-100">
				<a href="{{ url_for('bp_profile.list_gejala')}}">List Symptoms</a>
			</div>
		</div>
		<div class="col-4">
			<div class="btnListDrug w-100">
				<a href="{{ url_for('bp_profile.list_drug')}}">List Drug</a>
			</div>
		</div>
	</div>

</div>


{% endblock %}

templates/content_admin_list_gejala.html
{% extends 'template_base.html' %} 
{% block title %}List Symptoms{% endblock %} 
{% block content %}



  <div class="container">
    <div class="row justify-content-center">
      <!-- {% for i in gejala %}
      <div class="cardListSymptoms shadow-lg">
        <h3>{{ i[1] }}</h3>
        <h3>{{i[2]}} ?</h3>
        <a href="{{ url_for('bp_profile.delete_gejala',gejalaId = i[0]) }}" class="btn btn-danger">DELETE</a>
      </div>
      {% endfor %} -->

      <table class="tableDisease mt-4">
        <thead>
          <tr>
            <th>NO</th>
            <th>NAME SYMPTOMS</th>
            <th>QUESTIONS OF SYMPTOMS</th>
            <th>ACTION</th>
          </tr>
        </thead>
        <tbody>
          {% for i in gejala %}
            <tr>
              <td>{{ loop.index + pagination.skip }}</td>
              <td>{{ i[1] }}</td>
              <td>{{ i[2] }}</td>
              <td><a href="{{ url_for('bp_profile.delete_gejala',gejalaId = i[0]) }}" class="btn btn-danger">DELETE</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>







      <div class="text-center mt-4 mb-2">
        {{ pagination.info }}
      </div>
      <div class="wrappagination mb-4">
        {{ pagination.links }} 
      </div>

      {% if session['role'] == 'dokter' %}
      <a href="{{ url_for('bp_profile.page_add_gejala') }}" class="btn btn-dark">Add SYMPTOMS</a>
      {% endif %}
    </div>
  </div>


{% endblock %}

templates/content_admin_list_penyakit.html
{% extends 'template_base.html' %} 
{% block title %}List Disease{% endblock %} 
{% block content %}


<div id="view"> 
  <div class="container">
    <div class="row justify-content-center">
      <table class="tableDisease mt-4">
        <thead>
          <tr>
            <th>NO</th>
            <th>NAME DISEASE</th>
            <th>LEVEL</th>
            <th>ACTION</th>
          </tr>
        </thead>
        <tbody>
          {% for i in penyakit %}
            <tr>
              <td>{{ loop.index + pagination.skip }}</td>
              <td>{{ i[1] }}</td>
              <td>{{ i[3] }}</td>
              <td><a href="{{ url_for('bp_profile.delete_penyakit',penyakitId = i[0]) }}" class="btn btn-danger">DELETE</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      
      <div class="text-center mt-4 mb-2">
        {{ pagination.info }}
      </div>
      <div class="wrappagination mb-4">
        {{ pagination.links }} 
      </div>
      {% if session['role'] == 'dokter' %}
      <a href="{{ url_for('bp_profile.page_add_penyakit') }}" class="btn btn-dark">Add DISEASE</a>
      {% endif %}
    </div>
    
  </div>
    
      
      
    

</div>   


{% endblock %}

templates/content_admin_list_user.html
{% extends 'template_base.html' %} 
{% block title %}List User{% endblock %} 
{% block content %}



    <div id="view"> 
        <div id="container">
           
                <!-- row 01 -->
                <div class="row justify-content-center">
           
                    <table class="tableDisease mt-4">
                        <thead>
                          <tr>
                            <th>NO</th>
                            <th>NAMA PENYAKIT</th>
                            <th>LEVEL</th>
                            <th>ACTION</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for i in list_user %}
                            <tr>
                              <td>{{ loop.index}}</td>
                              <td>{{ i[1] }}</td>
                              <td>{{ i[0] }}</td>
                              <td><a href="{{ url_for('bp_profile.delete_penyakit',penyakitId = i[0]) }}" class="btn btn-danger">DELETE</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                </div>   
        </div>
    </div>
            



</div>   

{% endblock %}

templates/content_dokter_homepage.html
{% extends 'template_base.html' %} 
{% block title %}Doktor - Pardoc{% endblock %} 
{% block content %}


{% with messages = get_flashed_messages() %}
{% if messages %}
<section class="testimonials">
<div class="row">
	<div class="large-12 large-centered column">
	<h3>ERROR</h3>
	<span>
	{% for message in messages %}
	{{ message }}
	{% endfor %}
	</span><p></p>
</div>
</div>
</section>
{% endif %}
{% endwith %}


<div class="container">
	<div class="btnListUser col-12">
		<a href="{{ url_for('bp_chat.content_list_chat')}}">CHAT PATIENT</a>
	</div>
	
	<div class="row justify-content-center">
		<div class="col-4">
			<div class="btnListDisease w-100">
				<a href="{{ url_for('bp_profile.list_penyakit')}}">LIST DISEASE</a>
			</div>
		</div>
		<div class="col-4">
			<div class="btnListSymtoms w-100">
				<a href="{{ url_for('bp_profile.list_gejala')}}">LIST SYMPTOMS</a>
			</div>
		</div>
		<div class="col-4">
			<div class="btnListDrug w-100">
				<a href="{{ url_for('bp_profile.list_drug')}}">LIST DRUG</a>
			</div>
		</div>
	</div>

</div>



{% endblock %}

templates/content_dokter_user_chat.html
{% extends 'template_base.html' %} 
{% block title %}List Chat Pasien{% endblock %} 
{% block content %}


<!-- {{ pasien }} -->

<!-- {% if pasien %}


    {% for i in pasien %}


        <a href="{{ url_for('bp_chat.content_private_chat',userId = i[0]) }}">
            <div class="card">
                <div class="card-header">
                {{ i[7] }}
                </div>
                <div class="card-body">
                <h5 class="card-title">{{i[1]}}</h5>
                <p class="card-text">{{i[4]}}</p>
                </div>
            </div>
        </a>

  {% endfor %}

{% endif %} -->


{% if pasien %}
<div id="view"> 

    
    <div id="container">
       
        {% for i in pasien %}
        <a href="{{ url_for('bp_chat.content_private_chat',userId = i[0]) }}">
            <div class="row justify-content-center" >
                <div class="cardListUser" style="background-color:white;">
                    <h5 class="card-title">{{i[1]}}</h5>
                    <h3 class="jobtype">{{i[4]}}</h3>
                </div>
            </div>   
        </a>
        {% endfor %}
    </div>


</div>
{% endif %}


{% endblock %}

templates/content_history.html
{% extends 'template_base.html' %} 
{% block title %}List History{% endblock %} 
{% block content %}

<div class="container">
    <div class="row justify-content-center">
       
      <table class="tableDisease mt-4">
        <thead>
          <tr>
            <th>ID</th>
            <th>USER NAME</th>
            <th>DATE</th>
            <th>DISEASE NAME</th>
            <th>DRUG RECOMENDATION</th>
          </tr>
        </thead>
        <tbody>
          {% for i in data_pages %}
            <tr>
              <td>{{i[0]}}</td>
              <td>{{ session['name'] }}</td>
              <td>{{i[6]}}</td>
              <td>{{i[8]}}</td>
              <td>{{i[9]}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <div class="text-center mt-4 mb-2">
        {{ pagination.info|safe }}
      </div>
      <div class="wrappagination mb-4">
        {{ pagination.links }} 
      </div>


    </div>
  </div>

{% endblock %}

templates/content_private_chat.html
{% extends 'template_base.html' %} 
{% block title %}Private Chat{% endblock %} 
{% block content %}

<div id="view"> 
{% if array_chat %}
    {% for i in array_chat %}
        <div class="row justify-content-center">
            
                {% if i[1] == session['userId'] %}
                <div class="cardChat shadow-lg" style="background-color: white; ">
                    <p>{{ i[3] }}</p>
                    <span class="time-left" >{{ i[5] }}</span>
                </div>
                {% else %}
                <div class="cardChat shadow-lg" style="background-color: #ddd; " >
                <div class="time-right" >
                    <p>{{ i[3] }}</p>
                    <span class="">{{ i[5] }}</span>
                </div>
                
                
                </div>
                {% endif %}
            </div>
        </div>   
    {% endfor %}
{% endif %}


<div class="wrappagination" >
{% if session['role'] == user %}
    <div class="chatbox-area">
        <form action="/send" method="post">
            <textarea placeholder="Talk to me!" class="chatbox" name="chat" id="chat" resize: "none" minlength="2"></textarea>
            <input class="submit-button" type="submit" value="send">
        </form>
    </div>
{% else %}
<div class="chatbox-area">
    <form action="{{ url_for('bp_chat.content_send_chat',user= user) }}" method="post">
        <textarea placeholder="Talk to me!" class="chatbox" name="chat" id="chat" resize: "none" minlength="2"></textarea>
        <input class="submit-button" type="submit" value="send">
    </form>
</div>
{% endif %}
</div>
{% endblock %}

</div>

templates/login.html
{% extends 'template_base.html' %} 
{% block title %}Login - Pardoc{% endblock %} 
{% block content %}


{% with messages = get_flashed_messages() %}
{% if messages %}
<section class="testimonials">
<div class="row">
	<div class="large-12 large-centered column">
	<h3>ERROR</h3>
	<span>
	{% for message in messages %}
	{{ message }}
	{% endfor %}
	</span><p></p>
</div>
</div>
</section>
{% endif %}
{% endwith %}

<!-- <section class="contact" id="contact">

              <form action="login" method="POST">
                   <div class="inputEmail">
                      <label class="emailText">Email:</label>
                       <input type="email" name="email" title="Email" class="defaultText defaultTextActive"  required> 
                   </div>
                  <div class="large-6 column">
                      <label>Password:</label>
                       <input type="password" name="password" title="Password" class="defaultText defaultTextActive"  required> 
                  </div>
                  <div class="large-12 column">
                      <input type="submit" value="login" class="cta" >
                  </div> 
              </form>
          </div>
      </div>

  
  </section> -->


    <section class="position-relative">
        
        <div class="container" >
            <div class="row mb-3">
                <div class="col-md-4 col-xl-6 text-center mx-auto">
                    <h2>LOGIN</h2>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center shadow-lg">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg class="bi bi-person" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div>
                            <form class="text-center" method="post" action="login">
                                <div class="mb-3"><input class="form-control" type="email" name="email" placeholder="Email" required /></div>
                                <div class="mb-3"><input class="form-control" type="password" name="password" placeholder="Password" required /></div>
                                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit" value="login" style="background-color:#F87474; border-color: #F87474;" >Login</button></div>
                                <p class="text-muted">not have an account? <a  href="{{ url_for('bp_register.register') }}" style="color:#F87474;">register here!</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


  


{% endblock %}